version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
    nodejs: "16"
  jobs:
    post_install:
      - npm install -g @mermaid-js/mermaid-cli

# Build documentation in the "src/" directory with Sphinx
sphinx:
  configuration: src/conf.py

# NB: mermaid diagrams currently broken on readthedocs PDF
formats:
  - pdf
  - epub

python:
   install:
     - requirements: requirements.txt
