name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: []

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: khan/pull-request-workflow-cancel@1.0.0
        with:
          workflows: "main.yml"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  sphinx-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
            sudo apt-get update && sudo apt-get install -y latexmk texlive-latex-extra
            pip install -r requirements.txt
            pip freeze

      - name: Build documentation
        run: |
          cd src
          make html
          make latexpdf
